[versions]
kotlin = "2.0.21"

[plugins]
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.2.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version = "1.12.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.1.0" }
spock = { module = "org.spockframework:spock-junit4", version = "2.4-M4-groovy-3.0" } # Must be "groovy-3.0" because Groovy is packaged in Gradle
